name: Make changelogs

on:
  push:
    branches:
    - dev

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == '4310V343k/RuBaystation12' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        run: |
          python tools/changelog/generate_cl.py
          echo "pr_number=$PR_NUM" >> $GITHUB_ENV
      - name: Commit and Push Changes
        run: |
          git config --local user.name "Changelogs"
          git config --local user.email "action@github.com"
          git commit -m "Automatic changelog generation for PR #${{ env.pr_number }} [ci skip]" -a
          git push
